import TanStackQueryProvider from '@/utils/TanstackProvider';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter';
import { ReactQueryDevtools } from '@tanstack/react-query-devtools';
import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import { Toaster } from 'react-hot-toast';
import StoreProvider from './StoreProvider';
import './globals.css';

const roboto = Roboto({
  weight: '400',
  subsets: ['latin']
});

export const metadata: Metadata = {
  title: 'Covid tracker',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <StoreProvider>
          <TanStackQueryProvider>
            <AppRouterCacheProvider>{children}</AppRouterCacheProvider>
            <ReactQueryDevtools
              initialIsOpen={false}
              buttonPosition="bottom-left"
              position="left"
            />
            <Toaster />
          </TanStackQueryProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
